import { z } from "zod";

export const createStudentSchema = z.object({
  fullName: z.string().min(1),
  registerNumber: z.string().min(1),
  rollNumber: z.string().optional().nullable(),
  admissionNumber: z.string().optional().nullable(),
  year: z.string().min(1),
  section: z.string().min(1),
  semester: z.number().int().optional().nullable(),
  academicYear: z.string().optional().nullable(),
  degree: z.string().optional().nullable(),
  batch: z.string().optional().nullable(),
  departmentId: z.string().min(1),
  mentorId: z.string().min(1),
  parentName: z.string().optional().nullable(),
  parentContact: z.string().optional().nullable(),
  email: z.string().email().optional().or(z.literal("")).nullable(),
  phone: z.string().optional().nullable(),
  dateOfBirth: z.string().datetime().optional().or(z.string().optional()).nullable(),
  gender: z.string().optional().nullable(),
  address: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  state: z.string().optional().nullable(),
  zipCode: z.string().optional().nullable(),
  careerGoal: z.string().optional().nullable(),
  targetRole: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  admissionYear: z.number().int().optional().nullable(),
  attendancePercentage: z.number().min(0).max(100).optional(),
  cgpa: z.number().min(0).max(10).optional(),
  arrearCount: z.number().int().min(0).optional(),
  placementStatus: z.enum(["NOT_ELIGIBLE", "ELIGIBLE", "IN_PROGRESS", "PLACED"]).optional(),
  internshipStatus: z.enum(["NOT_STARTED", "IN_PROGRESS", "COMPLETED"]).optional(),
  certificationCount: z.number().int().min(0).optional(),
});

export const updateStudentSchema = createStudentSchema.partial();
